// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"zg4-1/src/rk/week3/week3api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/search",
				Handler: SearchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/many_search",
				Handler: ManySearchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/pagination_search",
				Handler: PaginationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/synchronous",
				Handler: SynchronousHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upload",
				Handler: UploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/rollback",
				Handler: RollbackHandler(serverCtx),
			},
		},
	)
}
