// Code generated by goctl. DO NOT EDIT.
package types

type SearchRequest struct {
	Index   string `form:"index"`
	Keyword string `form:"keyword"`
}

type SearchResponse struct {
	Code string                 `json:"code"`
	Msg  string                 `json:"msg"`
	Data map[string]interface{} `json:"data"`
}

type ManySearchRequest struct {
	Index    string `form:"index"`
	Keyword  string `form:"keyword"`
	Keywords string `form:"keywords"`
}

type ManySearchResponse struct {
	Code string                 `json:"code"`
	Msg  string                 `json:"msg"`
	Data map[string]interface{} `json:"data"`
}

type PaginationSearchRequest struct {
	Index    string `form:"index"`
	Keyword  string `form:"keyword"`
	Page     int64  `form:"page"`
	PageSize int64  `form:"pageSize"`
}

type PaginationSearchResponse struct {
	Code string                 `json:"code"`
	Msg  string                 `json:"msg"`
	Data map[string]interface{} `json:"data"`
}

type SynchronousRequest struct {
	CourseName          string  `form:"courseName"`
	Score               float64 `form:"score"`
	MediumOfInstruction string  `form:"mediumOfInstruction"`
	CourseDescription   string  `form:"courseDescription"`
}

type SynchronousResponse struct {
	Code string                 `json:"code"`
	Msg  string                 `json:"msg"`
	Data map[string]interface{} `json:"data"`
}

type UploadRequest struct {
	FileVersion string `form:"fileVersion"`
	FileStatus  int64  `form:"fileStatus"`
}

type UploadResponse struct {
	Code string                 `json:"code"`
	Msg  string                 `json:"msg"`
	Data map[string]interface{} `json:"data"`
}

type RollbackRequest struct {
	Id          int64  `form:"id"`
	FileName    string `form:"fileName"`
	FileVersion string `form:"fileVersion"`
	FileStatus  int64  `form:"fileStatus"`
}

type RollbackResponse struct {
	Code string                 `json:"code"`
	Msg  string                 `json:"msg"`
	Data map[string]interface{} `json:"data"`
}
